<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="victoire.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="close-window.png" />
    <None Remove="fond.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="victoire.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="close-window.png" />
    <Resource Include="fond.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Images\fond.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
